### ISSUE TITLE
No calibration file for MIT dataset

### ISSUE THREAD

**Issue by alongqiyue** [tomas789/tonav#1]
Hi tomas:
    I had run tonav with mit dataset(2011-01-20-09-13-31.bag) follow the guide, but there is no calibration file for mit dataset and I can't run the program, can you provide one :)

**Comment by tomas789** [comment]
Hi @alongqiyue,

First of all thank you for your interest! There is my other repository called [tonav-supplementary-files](https://github.com/tomas789/tonav-supplementary-files) and it contains generic calibration in file [datasets/99_other_files/calibration.yaml](https://github.com/tomas789/tonav-supplementary-files/blob/master/datasets/99_other_files/calibration.yaml). But since Tonav only supports MSCKF propagation and update step (where all parameter estimation is done) you can fill in almost anything.

But don't lose hope :) I'm working on it!
